---
title: "Covariates + CBCL"
output: html_document
---

```{r}
covariates[c("h_edumc_None", "h_cohort", "h_parity_None", "h_native_None", "e3_sex_None")] <- lapply(
  covariates[c("h_edumc_None", "h_cohort", "h_parity_None","h_native_None","e3_sex_None")],
  as.factor
)
PFAS_codebook<-codebook[c(160:169),]
PFAS<-exposome[,c(PFAS_codebook$variable_name)]
PFAS<-cbind(exposome$ID, PFAS)
```


```{r}
library(dplyr)
PFAS<-rename(PFAS, ID = `exposome$ID`)
PFAS<-cbind(PFAS, phenotype$hs_Gen_Tot)
PFAS<-rename(PFAS, hs_Gen_Tot=`phenotype$hs_Gen_Tot`)
PFAS$behavior_concern<-vector(length=1301)
for (i in 1:1301) {
  score <- PFAS$hs_Gen_Tot[i]
  
  if (score < 60) {
    PFAS$behavior_concern[i] <- "Low"
  } else {
    PFAS$behavior_concern[i] <- "High"
  }
}
PFAS$behavior_concern<-as.factor(PFAS$behavior_concern)
PFAS$behavior_concern<-relevel(PFAS$behavior_concern, ref="Low")
Covariate_new = cbind(covariates, PFAS$hs_Gen_Tot, PFAS$behavior_concern)
Covariate_new = rename(Covariate_new, hs_Gen_Tot = `PFAS$hs_Gen_Tot`)
Covariate_new = rename(Covariate_new, behavior_concern = `PFAS$behavior_concern`) 
```

```{r}
confounding_covariates_test_data = cbind(covariates, phenotype$hs_Gen_Tot)
colnames(confounding_covariates_test_data)[16]<-"hs_Gen_Tot"
```


```{r}
for (i in 3:15) {
  var_name <- names(confounding_covariates_test_data)[i]
  cat("\n====================\n")
  cat("Model for:", var_name, "\n")
  cat("====================\n")
  predictor <- confounding_covariates_test_data[, i]
  model <- lm(hs_Gen_Tot ~ predictor, data = confounding_covariates_test_data)
  print(summary(model))
}
```

```{r}
data_merge = cbind(confounding_covariates_test_data, PFAS)
data_merge = data_merge[,-17]
data_merge = data_merge[,-16]
```


```{r}
for (i in 3:25) { 
  var1_name <- names(data_merge)[i]
  var2_name <- names(data_merge)[i + 1]
  
  cat("\n====================\n")
  cat("Testing if adding variable", var2_name, "to", var1_name, "improves the model beyond", var1_name, "alone\n")
  cat("====================\n")
  
  predictor1 <- data_merge[, i]
  predictor2 <- data_merge[, i + 1]
  
  model1 <- lm(hs_Gen_Tot.1 ~ predictor1, data = data_merge)
  model2 <- lm(hs_Gen_Tot.1 ~ predictor1 + predictor2, data = data_merge)
  
  print(anova(model1, model2))
}

```

