---
title: "Helix Table One"
author: "Leah Wood"
date: "2025-06-25"
output: pdf_document
---

```{r}
library(dplyr)
```

```{r}
#Read in the data
codebook<-read.csv("codebook.csv", header=T)
covariates<-read.csv("covariates.csv", header = T)
exposome<-read.csv("exposome.csv", header = T)
phenotype<-read.csv("phenotype.csv", header=T)
covariates<-covariates[,-1]
phenotype<-phenotype[,-1]
```

Table One for PFAS

```{r}
#First going to merge behavior with PFAS
PFAS_codebook<-codebook[c(160:169),]
PFAS<-exposome[,c(PFAS_codebook$variable_name)]
PFAS<-cbind(exposome$ID, PFAS)
PFAS<-rename(PFAS, ID = `exposome$ID`)
PFAS<-cbind(PFAS, phenotype$hs_Gen_Tot)
PFAS<-rename(PFAS, hs_Gen_Tot=`phenotype$hs_Gen_Tot`)
```

```{r}
#Now split the behavior
PFAS$behavior_concern<-vector(length=1301)
for (i in 1:1301) {
  score <- PFAS$hs_Gen_Tot[i]
  
  if (score < 60) {
    PFAS$behavior_concern[i] <- "Low"
  } else {
    PFAS$behavior_concern[i] <- "High"
  }
}
PFAS$behavior_concern<-as.factor(PFAS$behavior_concern)
PFAS$behavior_concern<-relevel(PFAS$behavior_concern, ref="Low")
```

```{r}
library(table1)
library(tableone)
```

```{r}
#Add Labels 
label(PFAS$hs_pfhxs_c_Log2)<- "PFHXS (C)"
label(PFAS$hs_pfhxs_m_Log2)<- "PFHXS (M)"
label(PFAS$hs_pfna_c_Log2)<- "PFNA (C)"
label(PFAS$hs_pfna_m_Log2)<- "PFNA (M)"
label(PFAS$hs_pfoa_c_Log2)<- "PFOA (C)"
label(PFAS$hs_pfoa_m_Log2)<- "PFOA (M)"
label(PFAS$hs_pfos_c_Log2)<- "PFOS (C)"
label(PFAS$hs_pfos_m_Log2)<- "PFOS (M)"
label(PFAS$hs_pfunda_c_Log2)<- "PFUNA (C)"
label(PFAS$hs_pfunda_m_Log2)<- "PFUNA (M)"
caption1<- "PFAS exposure (Log ng/mL) in Child Behavioral Categories"
footnote1<- "(C) = In Child / (M) = In Mother"
```

```{r}
table1(~hs_pfhxs_c_Log2+hs_pfhxs_m_Log2+hs_pfna_c_Log2+hs_pfna_m_Log2+hs_pfoa_c_Log2+hs_pfoa_m_Log2+hs_pfos_c_Log2+hs_pfos_m_Log2+hs_pfunda_c_Log2+hs_pfunda_m_Log2|behavior_concern,data=PFAS,overall=c(left="Total"), caption=caption1, footnote=footnote1)
```

```{r}
#check Assumptions
boxplot(hs_Gen_Tot~behavior_concern, data=PFAS)
hist(PFAS[PFAS$behavior_concern=="High",12])
hist(PFAS[PFAS$behavior_concern=="Low",12])
```

```{r}
#We will be going with a test that checks medians

pfas_vars <- names(PFAS)[2:11] 

pfas_pvals <- sapply(pfas_vars, function(var) {
  test <- wilcox.test(PFAS[[var]] ~ PFAS$behavior_concern)
  c(p.value = test$p.value, statistic = test$statistic)
})

# Convert to data frame for easier viewing
pfas_pvals <- as.data.frame(t(pfas_pvals))
pfas_pvals
```

Table One for Covariates

```{r}
#We are going to make a Table1 for Covariates

Covariate_new = cbind(covariates, PFAS$hs_Gen_Tot, PFAS$behavior_concern)
Covariate_new = rename(Covariate_new, hs_Gen_Tot = `PFAS$hs_Gen_Tot`)
Covariate_new = rename(Covariate_new, behavior_concern = `PFAS$behavior_concern`)              
```

```{r}
#We are making the covariates factors
Covariate_new$h_cohort = as.factor(Covariate_new$h_cohort)
Covariate_new$e3_sex_None = as.factor(Covariate_new$e3_sex_None)
Covariate_new$e3_yearbir_None = as.factor(Covariate_new$e3_yearbir_None)
Covariate_new$h_edumc_None = as.factor(Covariate_new$h_edumc_None)
Covariate_new$h_native_None = as.factor(Covariate_new$h_native_None)
Covariate_new$h_parity_None = as.factor(Covariate_new$h_parity_None)
```

```{r}
# Releveling
```

```{r}
# Adding labels
label(Covariate_new$h_cohort) = "Cohort"
label(Covariate_new$e3_sex_None) = "Sex"
label(Covariate_new$e3_yearbir_None) = "Birth Year (Child)"
label(Covariate_new$h_mbmi_None) = "BMI (Mother)"
label(Covariate_new$hs_wgtgain_None) = "Weight Gain (Pregnancy) (kg)"
label(Covariate_new$e3_gac_None) = "Gest. Age at Birth (Weeks)"
label(Covariate_new$h_age_None) = "Age (Mother)"
label(Covariate_new$h_edumc_None) = "Education Level (Mother)"
label(Covariate_new$h_native_None) = "Nativity (Parents)"
label(Covariate_new$h_parity_None) = "Parity"
label(Covariate_new$hs_child_age_None) = "Age (Child)"
label(Covariate_new$hs_c_height_None) = "Height (Child) (m)"
label(Covariate_new$hs_c_weight_None) = "Weight (Child) (kg)"
```


```{r}
caption2 = "Covariates in Child Behavioral Categories"
```

```{r}
library(table1)
table1(~h_cohort + e3_sex_None + e3_yearbir_None + h_mbmi_None + hs_wgtgain_None + e3_gac_None + h_age_None + h_edumc_None + h_native_None + h_parity_None + hs_child_age_None + hs_c_height_None + hs_c_weight_None | behavior_concern, data=Covariate_new, overall = c(left = "Total"), caption = caption2)

```

```{r}
#Get P-vals
cov_vars_cont <- names(Covariate_new)[c(5,6,7,8,12,13,14)] 

cov_pvals <- sapply(cov_vars_cont, function(var) {
  test <- wilcox.test(Covariate_new[[var]] ~ Covariate_new$behavior_concern)
  c(p.value = test$p.value, statistic = test$statistic)
})

# Convert to data frame for easier viewing
cov_pvals <- as.data.frame(t(cov_pvals))
cov_pvals
```

```{r}
#Get P-vals
cov_vars_cat <- names(Covariate_new)[c(2,3,4,9,10,11)] 


cov_pvals2 <- sapply(cov_vars_cat, function(var) {
  tab<-table(Covariate_new[[var]],Covariate_new$behavior_concern)
  test <- chisq.test(tab)
  c(p.value = test$p.value, statistic = test$statistic)
})

# Convert to data frame for easier viewing
cov_pvals2 <- as.data.frame(t(cov_pvals2))
cov_pvals2
```

Table 1 For Proteome

```{r}
proteome<-t(as.data.frame(proteome.d))
```

```{r}

df_large_subset <- PFAS[rownames(proteome),]

proteome <- cbind(proteome, df_large_subset)
proteome<-proteome[,-(37:49)]
caption3<-"Proteins and Child Behavioral Categories"
```

```{r}
table1(~ Adiponectin + CRP + APO.A1 + APO.B + APO.E + IL1beta + IL6 + MCP1 + Leptin + HGF + INSULIN + TNFalfa + BAFF + Cpeptide + PAI1 + IL8 + FGFBasic + GCSF + IL10 + IL13 + IL12 + Eotaxin + IL17 + MIP1alfa + MIP1beta + IL15 + EGF + IL5 + IFNgamma + IFNalfa + IL1RA + IL2 + IP10 + IL2R + MIG + IL4
| behavior_concern, data=proteome, overall = c(left = "Total"), caption = caption3)
```

```{r}
proteome_vars <- names(proteome)[1:36] 

prot_pvals <- sapply(proteome_vars, function(var) {
  test <- t.test(proteome[[var]] ~ proteome$behavior_concern)
  c(p.value = test$p.value, statistic = test$statistic)
})

# Convert to data frame for easier viewing
prot_pvals <- as.data.frame(t(prot_pvals))
prot_pvals
```


